### ISSUE TITLE
Can't add bots outside of the wizard, add button doesn't work

### ISSUE THREAD

**Issue by reddeath68** [MaggiWuerze/xddcwebloader#61]

**Comment by MaggiWuerze** [comment]
What exactly do you mean when you say "doesn't work" did you get an error or is just nothing happening in the ui?

**Comment by reddeath68** [comment]
> What exactly do you mean when you say "doesn't work" did you get an error or is just nothing happening in the ui?

Literally nothing happens. I even tried using tab to highlight the button and use enter or space to activate it thinking it could be a click box issue.

**Comment by MaggiWuerze** [comment]
So the popover doesn't open or it doesn't send the form?

**Comment by reddeath68** [comment]
> So the popover doesn't open or it doesn't send the form?

I fill out the text fields, and click the green button and nothing happens. The popup doesn't close, a bot is not added, literally nothing. It is like the run event is missing for the button.

**Comment by MaggiWuerze** [comment]
Ah got it, I think this is also fixed with the next release.

**Comment by reddeath68** [comment]
> Ah got it, I think this is also fixed with the next release.

I hope so, the project has a lot of potential. Would be even better if the jar created a UI as well instead of having to open a separate browser to use the program

**Comment by MaggiWuerze** [comment]
This should be fixed in [v0.5.3-BETA](https://github.com/MaggiWuerze/xddcwebloader/tree/v0.5.3-BETA) if you want to try

**Comment by reddeath68** [comment]
> This should be fixed in [v0.5.3-BETA](https://github.com/MaggiWuerze/xddcwebloader/tree/v0.5.3-BETA) if you want to try

I did and both problems persist. maybe there was an error with the old database, where is it stored so I can remove it and start fresh?

**Comment by MaggiWuerze** [comment]
If you don't specify anything else (currently done through env variables or the docker-compose file) it creates an H2 database in your home folder (~/data/ or %USERPROFILE%/data)

**Comment by reddeath68** [comment]
> If you don't specify anything else (currently done through env variables or the docker-compose file) it creates an H2 database in your home folder (~/data/ or %USERPROFILE%/data)

seems to be working now. Now to check out the function of downloading

**Comment by reddeath68** [comment]
Spoke too soon, the not adding spaces bug is back when trying to add a third bot.

**Comment by MaggiWuerze** [comment]
Sorry your still having trouble.
I've just created a dozen bots and I can't reproduce the error anymore. I really don't know how it could still be there since the problem came from me putting the button inside the tab headings, which is no longer the case.

Can you maybe describe the state your in? how many servers/channels/bots do you have and how did you create them?

**Comment by reddeath68** [comment]
> Sorry your still having trouble. I've just created a dozen bots and I can't reproduce the error anymore. I really don't know how it could still be there since the problem came from me putting the button inside the tab headings, which is no longer the case.
> 
> Can you maybe describe the state your in? how many servers/channels/bots do you have and how did you create them?

Started the jar file in terminal on a system running Ubuntu 20.04 using the command "java -jar xdccloader.jar". I currently use Java version 17.0.1 and nodejs version 17.9.0

As for once the program starts. If I use the setup wizard to add the bot on a fresh DB I can add the bot fine, but if I try to add a second bot via the plus button under bots and filling out the info fields, the space key stops working after adding the first bot. This mostly seems to impact the pattern field in particular. I doubt it is relevant but I am trying to add the bots from this packlist https://animk.info/xdcc/

**Comment by MaggiWuerze** [comment]
I'll try it on my Ubuntu machine later, although that should not have an impact.

**Comment by reddeath68** [comment]
> I'll try it on my Ubuntu machine later, although that should not have an impact.

Also I am running firefox version 103

**Comment by MaggiWuerze** [comment]
Yeah, Firefox is my main testing browser :wink:
